# Caso 4 - Riesgos
### Jimena Chacón (B81999)

In [49]:
!pip install statsmodels

Collecting statsmodels
  Downloading statsmodels-0.14.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.2 kB)
Requirement already satisfied: numpy<3,>=1.22.3 in /home/codespace/.local/lib/python3.12/site-packages (from statsmodels) (2.1.1)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /home/codespace/.local/lib/python3.12/site-packages (from statsmodels) (1.14.1)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in /home/codespace/.local/lib/python3.12/site-packages (from statsmodels) (2.2.3)
Collecting patsy>=0.5.6 (from statsmodels)
  Downloading patsy-0.5.6-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: packaging>=21.3 in /home/codespace/.local/lib/python3.12/site-packages (from statsmodels) (24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/codespace/.local/lib/python3.12/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.12/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2024.2)
Requirement already satisfied: six in /home/codespace/.local/lib/python3.12/site-packages (from patsy>=0.5.6->statsmodels) (1.16.0)
Downloading statsmodels-0.14.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 61.3 MB/s eta 0:00:00
Downloading patsy-0.5.6-py2.py3-none-any.whl (233 kB)
Installing collected packages: patsy, statsmodels
Successfully installed patsy-0.5.6 statsmodels-0.14.4

In [50]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, roc_auc_score, accuracy_score, confusion_matrix,  roc_curve, auc
import seaborn as sns
import statsmodels.formula.api as smf

In [1]:


# Carga del dataset
data = pd.read_csv('train.csv')

NameError: name 'pd' is not defined

Variable Dependiente: Credit Score

In [6]:
data['Credit_Score'].unique()
data['Credit_Score'].value_counts()
data['malo']=data['Credit_Score'].map({'Good':0, 'Standard':0, 'Poor':1})
data['malo'].value_counts()

malo
0    71002
1    28998
Name: count, dtype: int64

Variables independientes: Edad

In [34]:
data['Age'].unique()

array(['23', '28_', '28', '34', '54', '55', '21', '31', '33', '34_', '30',
       '30_', '24', '24_', '44', '45', '40', '41', '32', '33_', '35',
       '35_', '36', '39', '37', '20', '46', '26', '42', '19', '31_', '48',
       '40_', '37_', '38', '54_', '43', '21_', '22', '18', '20_', '27',
       '43_', '38_', '25', '18_', '46_', '47', '19_', '47_', '53_', '53',
       '56', '25_', '27_', '55_', '29', '42_', '48_', '49', '49_', '51',
       '50', '50_', '32_', '22_', '29_', '52', '51_', '26_', '39_', '36_',
       '44_', '45_', '23_', '41_', '52_', '56_'], dtype=object)

In [36]:
data['Edad'] = data['Age'].str.replace('_','')
data['Edad'] = pd.to_numeric(data['Edad'],errors='coerce')
data['Edad'].isna().sum()
data = data.loc[(data['Edad']<=90)&(data['Edad']>=18),:].copy()

In [35]:
data['EdadCat'] = pd.cut(data['Edad'],bins = 5)
data

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score,malo,Edad,EdadCat
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good,0,23,"(17.962, 25.6]"
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good,0,23,"(17.962, 25.6]"
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good,0,23,"(17.962, 25.6]"
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good,0,23,"(17.962, 25.6]"
5,0x1607,CUS_0xd40,June,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,22 Years and 6 Months,No,49.574949,62.430172331195294,!@9#%8,340.4792117872438,Good,0,23,"(17.962, 25.6]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,0x25fe9,CUS_0x942c,April,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,...,31 Years and 6 Months,No,35.104023,60.97133255718485,High_spent_Large_value_payments,479.866228,Poor,1,25,"(17.962, 25.6]"
99996,0x25fea,CUS_0x942c,May,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,...,31 Years and 7 Months,No,35.104023,54.18595028760385,High_spent_Medium_value_payments,496.65161,Poor,1,25,"(17.962, 25.6]"
99997,0x25feb,CUS_0x942c,June,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,...,31 Years and 8 Months,No,35.104023,24.02847744864441,High_spent_Large_value_payments,516.809083,Poor,1,25,"(17.962, 25.6]"
99998,0x25fec,CUS_0x942c,July,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,...,31 Years and 9 Months,No,35.104023,251.67258219721603,Low_spent_Large_value_payments,319.164979,Standard,0,25,"(17.962, 25.6]"
99999,0x25fed,CUS_0x942c,August,Nicks,25,078-73-5990,Mechanic,39628.99_,3359.415833,4,...,31 Years and 10 Months,No,35.104023,167.1638651610451,!@9#%8,393.673696,Poor,1,25,"(17.962, 25.6]"

In [37]:
data['EdadCat'].value_counts()

EdadCat
(25.6, 33.2]      22616
(17.962, 25.6]    21652
(33.2, 40.8]      19762
(40.8, 48.4]      17795
(48.4, 56.0]       9688
Name: count, dtype: int64

In [38]:
dfTablaWoeEdad = data[['EdadCat','malo']].groupby('EdadCat').agg({'malo':['sum','count']})
dfTablaWoeEdad.columns = ['malo','total']
dfTablaWoeEdad['probMalo'] = dfTablaWoeEdad['malo'] / dfTablaWoeEdad['total']
dfTablaWoeEdad

/tmp/ipykernel_8623/1244614602.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dfTablaWoeEdad = data[['EdadCat','malo']].groupby('EdadCat').agg({'malo':['sum','count']})

                malo  total  probMalo
EdadCat
(17.962, 25.6]  6657  21652  0.307454
(25.6, 33.2]    7017  22616  0.310267
(33.2, 40.8]    6078  19762  0.307560
(40.8, 48.4]    4774  17795  0.268278
(48.4, 56.0]    1114   9688  0.114988

In [53]:
dfTablaWoeEdad['bueno'] = dfTablaWoeEdad['total']-dfTablaWoeEdad['malo']
dfTablaWoeEdad['distBad'] = dfTablaWoeEdad['malo'] / dfTablaWoeEdad['malo'].sum() 
dfTablaWoeEdad['distGood'] = dfTablaWoeEdad['bueno'] / dfTablaWoeEdad['bueno'].sum()
dfTablaWoeEdad['woe_edad'] = np.log(dfTablaWoeEdad['distBad']/dfTablaWoeEdad['distGood'])
dfTablaWoeEdad

                malo  total  probMalo  bueno   distBad  distGood  woe_edad
EdadCat
(17.962, 25.6]  6657  21652  0.307454  14995  0.259633  0.227635  0.131527
(25.6, 33.2]    7017  22616  0.310267  15599  0.273674  0.236804  0.144704
(33.2, 40.8]    6078  19762  0.307560  13684  0.237051  0.207733  0.132023
(40.8, 48.4]    4774  17795  0.268278  13021  0.186193  0.197668 -0.059804
(48.4, 56.0]    1114   9688  0.114988   8574  0.043448  0.130160 -1.097202

In [64]:
dfTablaWoeEdad.reset_index(inplace=True)

In [65]:
data['EdadCat'] = data['EdadCat'].astype(str)
data = pd.merge(data,dfTablaWoeEdad[['EdadCat','woe_edad']],on='EdadCat')

In [67]:
model = smf.logit('malo ~ woe_edad', data=data).fit()
print(model.summary())

ValueError: zero-size array to reduction operation maximum which has no identity